teacherOf(severus_snape, harry_potter).
teacherOf(severus_snape, ron_weasley).
teacherOf(severus_snape, draco_malfoy).
teacherOf(severus_snape, hermione_granger).
teacherOf(severus_snape, ginny_weasley).
teacherOf(severus_snape, fred_weasley).
teacherOf(severus_snape, bill_weasley).
teacherOf(minerva_mcgonagall, harry_potter).
teacherOf(minerva_mcgonagall, ron_weasley).
teacherOf(minerva_mcgonagall, hermione_granger).
teacherOf(sybill_trelawney, harry_potter).
teacherOf(sybill_trelawney, ron_weasley).
teacherOf(sybill_trelawney, hermione_granger).
teacherOf(sybill_trelawney, oliver_wood).
teacherOf(sybill_trelawney, cho_chang).

directSeniorOf(albus_dumbledore, minerva_mcgonagall).
directSeniorOf(minerva_mcgonagall, james_potter).
directSeniorOf(james_potter, severus_snape).
directSeniorOf(james_potter, rubeus_hagrid).
directSeniorOf(rubeus_hagrid, bill_weasley).
directSeniorOf(bill_weasley, fred_weasley).
directSeniorOf(fred_weasley, ron_weasley).
directSeniorOf(ron_weasley, ginny_weasley).


birthYear(harry_potter, 1980).
birthYear(hermione_granger, 1979).
birthYear(ron_weasley, 1981).
birthYear(albus_dumbledore, 1881).
birthYear(rubeus_hagrid, 1928).
birthYear(james_potter, 1960).
birthYear(ginny_weasley, 1986).
birthYear(fred_weasley, 1978).
birthYear(percy_weasley, 1976).
birthYear(bill_weasley, 1972).
birthYear(charlie_weasley, 1970).
birthYear(draco_malfoy, 1982).
birthYear(severus_snape, 1961).
birthYear(minerva_mcgonagall, 1935).
birthYear(oliver_wood, 1969).
birthYear(alicia_spinnet, 1955).
birthYear(millicent_bulstrode, 2000).
birthYear(daphne_greengrass, 1962).
birthYear(adrian_pucey, 1963).
birthYear(terence_higgs, 1975).
birthYear(marcus_flint, 1964).
birthYear(gregory_goyle, 1965).
birthYear(cedric_diggory, 1966).
birthYear(ernie_macmillan, 1958).
birthYear(newton_scamander, 1959).
birthYear(susan_bones, 1957).
birthYear(david_smith, 1949).
birthYear(eli_olivander, 1954).
birthYear(vince_glover, 1953).
birthYear(sean_richards, 1951).
birthYear(sybill_trelawney, 1991).
birthYear(terry_boot, 1992).
birthYear(anthony_goldstein, 1993).
birthYear(jason_samuels, 1994).
birthYear(duncan_inglebee, 1995).
birthYear(jeremy_stretton, 1996).
birthYear(cho_chang, 1997).

houseOf(gryffindor, harry_potter).
houseOf(gryffindor, fred_weasley).
houseOf(gryffindor, ginny_weasley).
houseOf(gryffindor, ron_weasley).
houseOf(gryffindor, hermione_granger).
houseOf(gryffindor, bill_weasley).
houseOf(gryffindor, percy_weasley).
houseOf(gryffindor, oliver_wood).
houseOf(gryffindor, alicia_spinnet).
houseOf(slytherin, draco_malfoy).
houseOf(slytherin, millicent_bulstrode).
houseOf(slytherin, daphne_greengrass).
houseOf(slytherin, adrian_pucey).
houseOf(slytherin, terence_higgs).
houseOf(slytherin, marcus_flint).
houseOf(slytherin, gregory_goyle).
houseOf(hufflepuff, cedric_diggory).
houseOf(hufflepuff, ernie_macmillan).
houseOf(hufflepuff, newton_scamander).
houseOf(hufflepuff, susan_bones).
houseOf(hufflepuff, david_smith).
houseOf(hufflepuff, eli_olivander).
houseOf(hufflepuff, vince_glover).
houseOf(hufflepuff, sean_richards).
houseOf(ravenclaw, sybill_trelawney).
houseOf(ravenclaw, terry_boot).
houseOf(ravenclaw, anthony_goldstein).
houseOf(ravenclaw, jason_samuels).
houseOf(ravenclaw, duncan_inglebee).
houseOf(ravenclaw, jeremy_stretton).
houseOf(ravenclaw, cho_chang).

farLocation(gryffindor, slytherin).
farLocation(slytherin, gryffindor).
farLocation(gryffindor, hufflepuff).
farLocation(hufflepuff, gryffindor).
farLocation(slytherin, ravenclaw).
farLocation(ravenclaw, slytherin).
farLocation(hufflepuff, ravenclaw).
farLocation(ravenclaw, hufflepuff).


quidditchTeamOf(hufflepuff_team, david_smith).
quidditchTeamOf(hufflepuff_team, eli_olivander).
quidditchTeamOf(hufflepuff_team, vince_glover).
quidditchTeamOf(hufflepuff_team, sean_richards).

quidditchTeamOf(ravenclaw_team, duncan_inglebee).
quidditchTeamOf(ravenclaw_team, jason_samuels).
quidditchTeamOf(ravenclaw_team, jeremy_stretton).
quidditchTeamOf(ravenclaw_team, cho_chang).

quidditchTeamOf(slytherin_team, draco_malfoy).
quidditchTeamOf(slytherin_team, terence_higgs).
quidditchTeamOf(slytherin_team, marcus_flint).
quidditchTeamOf(slytherin_team, gregory_goyle).

quidditchTeamOf(gryffindor_team, oliver_wood).
quidditchTeamOf(gryffindor_team, fred_weasley).
quidditchTeamOf(gryffindor_team, alicia_spinnet).
quidditchTeamOf(gryffindor_team, harry_potter).
